name: Development

on:
  push:
    branches: [ "development" ]
    paths:
      - '**'
      - '.github/workflows/development.yml'
  pull_request:
    branches: ["development"]

env:
  REQUIREMENTS_FILE: ./cfn/requirements.txt

jobs:
  build:
    runs-on: ubuntu-latest
    environment: development

    steps:
    - name: Checkout
      uses: actions/checkout@v2

    - name: Setup Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.x'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r ${{ env.REQUIREMENTS_FILE }}

    - name: Run tests
      run: |
        pytest